In [5]:
import pandas as pd
import numpy as np
import warnings
import os

In [6]:
warnings.filterwarnings("ignore")

In [7]:
DATA_PATH = "/Volumes/T7/DS Projects/Chicago Ride Demand Forecasting/data/raw/CHI001RDE_20260207.csv"

if os.path.exists(DATA_PATH):
    file_size_gb = os.path.getsize(DATA_PATH) / (1024 * 1024 * 1024)
    print(f"File size: {file_size_gb:.2f} GB")
else:
    raise FileNotFoundError(f"File not found: {DATA_PATH}")

df_raw = pd.read_csv(DATA_PATH)
print(df_raw.shape)

File size: 2.36 GB
(7812937, 24)

In [8]:
df_raw.head()

,Trip ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Percent Time Chicago,Percent Distance Chicago,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,...,Trip Total,Shared Trip Authorized,Shared Trip Match,Trips Pooled,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location
0,f6610dffa8bca5e94270130e07362acc8a39962a,12/31/2024 11:45:00 PM,12/31/2024 11:45:00 PM,300,0.9,99%,100%,1.703132e+10,1.703133e+10,32.0,...,$8.06,False,False,1,41.870607,-87.622173,POINT (-87.6221729369 41.8706073724),41.859350,-87.617358,POINT (-87.6173580061 41.859349715)
1,f6646c9c149464a718f0f06c1f77ad36aad3a40c,12/31/2024 11:45:00 PM,01/01/2025 12:00:00 AM,860,4.6,100%,100%,1.703106e+10,1.703124e+10,6.0,...,$19.5,False,False,1,41.949061,-87.661643,POINT (-87.6616429039 41.9490605256),41.892537,-87.659864,POINT (-87.6598643178 41.8925368719)
2,f6a36a42e96b8b2b58dfa95360bad942dd55da46,12/31/2024 11:45:00 PM,01/01/2025 12:00:00 AM,275,1.1,100%,100%,NaN,NaN,6.0,...,$10.39,False,False,1,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),41.947792,-87.683835,POINT (-87.6838349425 41.9477915865)
3,f6c084f804b0a541751e673ed15031b9943e04d5,12/31/2024 11:45:00 PM,01/01/2025 12:00:00 AM,"1,081",6.7,100%,100%,NaN,NaN,38.0,...,$8.81,True,True,4,41.812949,-87.617860,POINT (-87.6178596758 41.8129489392),41.777196,-87.642498,POINT (-87.6424975271 41.7771962546)
4,f70eebf81e9bf34412c1c27e572835cd2317bc83,12/31/2024 11:45:00 PM,12/31/2024 11:45:00 PM,588,0.6,100%,100%,1.703108e+10,1.703108e+10,8.0,...,$7.63,False,False,1,41.890922,-87.618868,POINT (-87.6188683546 41.8909220259),41.892508,-87.626215,POINT (-87.6262149064 41.8925077809)

In [9]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7812937 entries, 0 to 7812936
Data columns (total 24 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Trip ID                     object
 1   Trip Start Timestamp        object
 2   Trip End Timestamp          object
 3   Trip Seconds                object
 4   Trip Miles                  float64
 5   Percent Time Chicago        object
 6   Percent Distance Chicago    object
 7   Pickup Census Tract         float64
 8   Dropoff Census Tract        float64
 9   Pickup Community Area       float64
 10  Dropoff Community Area      float64
 11  Fare                        object
 12  Tip                         object
 13  Additional Charges          object
 14  Trip Total                  object
 15  Shared Trip Authorized      bool
 16  Shared Trip Match           bool
 17  Trips Pooled                int64
 18  Pickup Centroid Latitude    float64
 19  Pickup Centroid Longitude   float64
 20  Pickup Centroid Location    object
 21  Dropoff Centroid Latitude   float64
 22  Dropoff Centroid Longitude  float64
 23  Dropoff Centroid Location   object
dtypes: bool(2), float64(9), int64(1), object(12)
memory usage: 1.3+ GB

In [10]:
df_raw.describe()

,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,Trips Pooled,Pickup Centroid Latitude,Pickup Centroid Longitude,Dropoff Centroid Latitude,Dropoff Centroid Longitude
count,7.812937e+06,4.849517e+06,4.836488e+06,7.074128e+06,7.049063e+06,7.812937e+06,7.096489e+06,7.096489e+06,7.068383e+06,7.068383e+06
mean,7.052837e+00,1.703140e+10,1.703141e+10,2.822914e+01,2.907451e+01,1.083220e+00,4.188568e+01,-8.767104e+01,4.188673e+01,-8.767428e+01
std,7.895440e+00,3.413359e+05,3.464529e+05,2.183581e+01,2.235851e+01,5.167200e-01,7.110383e-02,6.899594e-02,7.101976e-02,7.448080e-02
min,0.000000e+00,1.703101e+10,1.703101e+10,1.000000e+00,1.000000e+00,1.000000e+00,4.165022e+01,-8.791362e+01,4.165022e+01,-8.791362e+01
25%,1.900000e+00,1.703108e+10,1.703108e+10,8.000000e+00,8.000000e+00,1.000000e+00,4.186128e+01,-8.769226e+01,4.186379e+01,-8.769453e+01
50%,4.100000e+00,1.703128e+10,1.703128e+10,2.500000e+01,2.700000e+01,1.000000e+00,4.189251e+01,-8.765401e+01,4.189251e+01,-8.765430e+01
75%,9.400000e+00,1.703183e+10,1.703183e+10,3.800000e+01,4.000000e+01,1.000000e+00,4.193379e+01,-8.763087e+01,4.193544e+01,-8.763087e+01
max,3.730000e+02,1.703198e+10,1.703198e+10,7.700000e+01,7.700000e+01,3.900000e+01,4.202122e+01,-8.752995e+01,4.202122e+01,-8.752995e+01

In [11]:
df_raw.columns

Index(['Trip ID', 'Trip Start Timestamp', 'Trip End Timestamp', 'Trip Seconds',
       'Trip Miles', 'Percent Time Chicago', 'Percent Distance Chicago',
       'Pickup Census Tract', 'Dropoff Census Tract', 'Pickup Community Area',
       'Dropoff Community Area', 'Fare', 'Tip', 'Additional Charges',
       'Trip Total', 'Shared Trip Authorized', 'Shared Trip Match',
       'Trips Pooled', 'Pickup Centroid Latitude', 'Pickup Centroid Longitude',
       'Pickup Centroid Location', 'Dropoff Centroid Latitude',
       'Dropoff Centroid Longitude', 'Dropoff Centroid Location'],
      dtype='object')

In [12]:
df_raw.isnull().sum()

Trip ID                             0
Trip Start Timestamp                0
Trip End Timestamp                  0
Trip Seconds                        0
Trip Miles                          0
Percent Time Chicago            46057
Percent Distance Chicago        46468
Pickup Census Tract           2963420
Dropoff Census Tract          2976449
Pickup Community Area          738809
Dropoff Community Area         763874
Fare                             4391
Tip                              4391
Additional Charges               4391
Trip Total                       4391
Shared Trip Authorized              0
Shared Trip Match                   0
Trips Pooled                        0
Pickup Centroid Latitude       716448
Pickup Centroid Longitude      716448
Pickup Centroid Location       716448
Dropoff Centroid Latitude      744554
Dropoff Centroid Longitude     744554
Dropoff Centroid Location      744554
dtype: int64

In [13]:
missing_df  = pd.DataFrame({
    'Column': df_raw.columns,
    'Missing_count': df_raw.isnull().sum().values,
    'Missing_percent': (df_raw.isnull().sum().values / len(df_raw)) * 100,
    'Data_type': df_raw.dtypes.values
})

missing_df = missing_df.sort_values('Missing_percent', ascending=False)
missing_df = missing_df.reset_index(drop=True)
missing_df['Missing_percent'] = missing_df['Missing_percent'].round(2)
missing_df

                        Column  Missing_count  Missing_percent Data_type
0         Dropoff Census Tract        2976449            38.10   float64
1          Pickup Census Tract        2963420            37.93   float64
2       Dropoff Community Area         763874             9.78   float64
3    Dropoff Centroid Location         744554             9.53    object
4   Dropoff Centroid Longitude         744554             9.53   float64
5    Dropoff Centroid Latitude         744554             9.53   float64
6        Pickup Community Area         738809             9.46   float64
7     Pickup Centroid Location         716448             9.17    object
8    Pickup Centroid Longitude         716448             9.17   float64
9     Pickup Centroid Latitude         716448             9.17   float64
10    Percent Distance Chicago          46468             0.59    object
11        Percent Time Chicago          46057             0.59    object
12                  Trip Total           4391             0.06    object
13                         Tip           4391             0.06    object
14          Additional Charges           4391             0.06    object
15                        Fare           4391             0.06    object
16      Shared Trip Authorized              0             0.00      bool
17           Shared Trip Match              0             0.00      bool
18                Trips Pooled              0             0.00     int64
19        Trip Start Timestamp              0             0.00    object
20                  Trip Miles              0             0.00   float64
21                Trip Seconds              0             0.00    object
22          Trip End Timestamp              0             0.00    object
23                     Trip ID              0             0.00    object

In [14]:
for col in df_raw.columns:
    print(f"Column: {col}")
    print(f"Type: {df_raw[col].dtype}")
    print(f"Non-null: {df_raw[col].notna().sum():,} / {len(df_raw):,}")
    print(f"Unique values: {df_raw[col].nunique():,}")

    if df_raw[col].nunique() <= 10:
        print(f"Values: {df_raw[col].unique()}")
        print("-" * 80)
    else:
        print(f"Sample values: {df_raw[col].dropna().head(3).tolist()}")
        print("-" * 80)

Column: Trip ID
Type: object
Non-null: 7,812,937 / 7,812,937
Unique values: 7,812,937
Sample values: ['f6610dffa8bca5e94270130e07362acc8a39962a', 'f6646c9c149464a718f0f06c1f77ad36aad3a40c', 'f6a36a42e96b8b2b58dfa95360bad942dd55da46']
--------------------------------------------------------------------------------
Column: Trip Start Timestamp
Type: object
Non-null: 7,812,937 / 7,812,937
Unique values: 2,976
Sample values: ['12/31/2024 11:45:00 PM', '12/31/2024 11:45:00 PM', '12/31/2024 11:45:00 PM']
--------------------------------------------------------------------------------
Column: Trip End Timestamp
Type: object
Non-null: 7,812,937 / 7,812,937
Unique values: 2,985
Sample values: ['12/31/2024 11:45:00 PM', '01/01/2025 12:00:00 AM', '01/01/2025 12:00:00 AM']
--------------------------------------------------------------------------------
Column: Trip Seconds
Type: object
Non-null: 7,812,937 / 7,812,937
Unique values: 6,755
Sample values: ['300', '860', '275']
--------------------------------------------------------------------------------
Column: Trip Miles
Type: float64
Non-null: 7,812,937 / 7,812,937
Unique values: 1,735
Sample values: [0.9, 4.6, 1.1]
--------------------------------------------------------------------------------
Column: Percent Time Chicago
Type: object
Non-null: 7,766,880 / 7,812,937
Unique values: 215
Sample values: ['99%', '100%', '100%']
--------------------------------------------------------------------------------
Column: Percent Distance Chicago
Type: object
Non-null: 7,766,469 / 7,812,937
Unique values: 271
Sample values: ['100%', '100%', '100%']
--------------------------------------------------------------------------------
Column: Pickup Census Tract
Type: float64
Non-null: 4,849,517 / 7,812,937
Unique values: 1,227
Sample values: [17031320600.0, 17031061200.0, 17031081403.0]
--------------------------------------------------------------------------------
Column: Dropoff Census Tract
Type: float64
Non-null: 4,836,488 / 7,812,937
Unique values: 1,232
Sample values: [17031330100.0, 17031243400.0, 17031081500.0]
--------------------------------------------------------------------------------
Column: Pickup Community Area
Type: float64
Non-null: 7,074,128 / 7,812,937
Unique values: 77
Sample values: [32.0, 6.0, 6.0]
--------------------------------------------------------------------------------
Column: Dropoff Community Area
Type: float64
Non-null: 7,049,063 / 7,812,937
Unique values: 77
Sample values: [33.0, 24.0, 5.0]
--------------------------------------------------------------------------------
Column: Fare
Type: object
Non-null: 7,808,546 / 7,812,937
Unique values: 201
Sample values: ['$2.5', '$15', '$7.5']
--------------------------------------------------------------------------------
Column: Tip
Type: object
Non-null: 7,808,546 / 7,812,937
Unique values: 89
Sample values: ['$3', '$0', '$0']
--------------------------------------------------------------------------------
Column: Additional Charges
Type: object
Non-null: 7,808,546 / 7,812,937
Unique values: 6,934
Sample values: ['$2.56', '$4.5', '$2.89']
--------------------------------------------------------------------------------
Column: Trip Total
Type: object
Non-null: 7,808,546 / 7,812,937
Unique values: 17,994
Sample values: ['$8.06', '$19.5', '$10.39']
--------------------------------------------------------------------------------
Column: Shared Trip Authorized
Type: bool
Non-null: 7,812,937 / 7,812,937
Unique values: 2
Values: [False  True]
--------------------------------------------------------------------------------
Column: Shared Trip Match
Type: bool
Non-null: 7,812,937 / 7,812,937
Unique values: 2
Values: [False  True]
--------------------------------------------------------------------------------
Column: Trips Pooled
Type: int64
Non-null: 7,812,937 / 7,812,937
Unique values: 26
Sample values: [1, 1, 1]
--------------------------------------------------------------------------------
Column: Pickup Centroid Latitude
Type: float64
Non-null: 7,096,489 / 7,812,937
Unique values: 879
Sample values: [41.8706073724, 41.9490605256, 41.9442266014]
--------------------------------------------------------------------------------
Column: Pickup Centroid Longitude
Type: float64
Non-null: 7,096,489 / 7,812,937
Unique values: 878
Sample values: [-87.6221729369, -87.6616429039, -87.6559981815]
--------------------------------------------------------------------------------
Column: Pickup Centroid Location
Type: object
Non-null: 7,096,489 / 7,812,937
Unique values: 879
Sample values: ['POINT (-87.6221729369 41.8706073724)', 'POINT (-87.6616429039 41.9490605256)', 'POINT (-87.6559981815 41.9442266014)']
--------------------------------------------------------------------------------
Column: Dropoff Centroid Latitude
Type: float64
Non-null: 7,068,383 / 7,812,937
Unique values: 879
Sample values: [41.859349715, 41.8925368719, 41.9477915865]
--------------------------------------------------------------------------------
Column: Dropoff Centroid Longitude
Type: float64
Non-null: 7,068,383 / 7,812,937
Unique values: 878
Sample values: [-87.6173580061, -87.6598643178, -87.6838349425]
--------------------------------------------------------------------------------
Column: Dropoff Centroid Location
Type: object
Non-null: 7,068,383 / 7,812,937
Unique values: 879
Sample values: ['POINT (-87.6173580061 41.859349715)', 'POINT (-87.6598643178 41.8925368719)', 'POINT (-87.6838349425 41.9477915865)']
--------------------------------------------------------------------------------

##### Rename Columns

In [15]:
df = df_raw.copy()

df.columns = (
    df.columns.str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('percent', 'pct')
)

df.columns

Index(['trip_id', 'trip_start_timestamp', 'trip_end_timestamp', 'trip_seconds',
       'trip_miles', 'pct_time_chicago', 'pct_distance_chicago',
       'pickup_census_tract', 'dropoff_census_tract', 'pickup_community_area',
       'dropoff_community_area', 'fare', 'tip', 'additional_charges',
       'trip_total', 'shared_trip_authorized', 'shared_trip_match',
       'trips_pooled', 'pickup_centroid_latitude', 'pickup_centroid_longitude',
       'pickup_centroid_location', 'dropoff_centroid_latitude',
       'dropoff_centroid_longitude', 'dropoff_centroid_location'],
      dtype='object')

##### Fix Data Types in Currency Columns

In [16]:
currency_cols  = ['fare', 'tip', 'additional_charges', 'trip_total']

for col in currency_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace('$', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.strip()
    )

    df[col] = df[col].replace('nan', np.nan)
    df[col] = df[col].replace('', np.nan)
    df[col] = pd.to_numeric(df[col], errors='coerce')

##### Fix Percentage Column

In [17]:
pct_cols = ['pct_time_chicago', 'pct_distance_chicago']

for col in pct_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace('%', '', regex=False)
        .str.strip()
    )

    df[col] = df[col].replace('nan', np.nan)
    df[col] = df[col].replace('', np.nan)
    df[col] = pd.to_numeric(df[col], errors='coerce') / 100

##### Fix DateTime Columns

In [18]:
datetime_cols = ['trip_start_timestamp', 'trip_end_timestamp']

"""
%m = month (12)
%d = day (31)
%Y = 4-digit year (2024)
%I = 12-hour clock hour (11)
%M = minute (45)
%S = second (00)
%p = AM/PM

"""

for col in datetime_cols:
    df[col] = pd.to_datetime(df[col], format="%m/%d/%Y %I:%M:%S %p", errors='coerce')
    print(df[col].head())

0   2024-12-31 23:45:00
1   2024-12-31 23:45:00
2   2024-12-31 23:45:00
3   2024-12-31 23:45:00
4   2024-12-31 23:45:00
Name: trip_start_timestamp, dtype: datetime64[ns]
0   2024-12-31 23:45:00
1   2025-01-01 00:00:00
2   2025-01-01 00:00:00
3   2025-01-01 00:00:00
4   2024-12-31 23:45:00
Name: trip_end_timestamp, dtype: datetime64[ns]

##### Verify Date Range

In [19]:
start_col = 'trip_start_timestamp'
print(f"\nEarliest trip start: {df[start_col].min()}")
print(f"Latest trip start:   {df[start_col].max()}")
print(f"Date range span:     {(df[start_col].max() - df[start_col].min()).days} days")

# Distribution by date
print(f"\nTrips per day (first 5 and last 5):")
daily_counts = df[start_col].dt.date.value_counts().sort_index()
print("\nFirst 5 days:")
print(daily_counts.head().to_string())
print("\nLast 5 days:")
print(daily_counts.tail().to_string())
print(f"\nTotal unique dates: {daily_counts.shape[0]}")
# print(daily_counts)

Earliest trip start: 2024-12-01 00:00:00
Latest trip start:   2024-12-31 23:45:00
Date range span:     30 days

Trips per day (first 5 and last 5):

First 5 days:
trip_start_timestamp
2024-12-01    232068
2024-12-02    239219
2024-12-03    247799
2024-12-04    262813
2024-12-05    278925

Last 5 days:
trip_start_timestamp
2024-12-27    228420
2024-12-28    243810
2024-12-29    222300
2024-12-30    215900
2024-12-31    326363

Total unique dates: 31

##### Drop Rows Missing Critical Data

In [20]:
critical_cols = ['trip_start_timestamp', 'pickup_centroid_latitude', 'pickup_centroid_longitude']
critical_nulls = df[critical_cols].isnull().any(axis=1).sum()
print(f"Rows missing critical data: {critical_nulls:,}")

df = df.dropna(subset=critical_cols).reset_index(drop=True)

Rows missing critical data: 716,448

##### Drop Duplicate Trips

In [21]:
duplicate_count = df['trip_id'].duplicated().sum()

if duplicate_count > 0:
    df = df.drop_duplicates(subset='trip_id', keep='first').reset_index(drop=True)
else:
    print("No duplicate trip_id values found.")

No duplicate trip_id values found.

##### Remove Outliers

In [29]:
# Filter Duration
df['trip_seconds'] = pd.to_numeric(df['trip_seconds'], errors='coerce')
mask_duration = (df['trip_seconds'] > 0) & (df['trip_seconds'] <= 10800)
removed_duration = (~mask_duration).sum()
print(f"\nRemoving {removed_duration:,} trips with invalid durations.")

# Filter Distance
mask_distance = (df['trip_miles'] > 0) & (df['trip_miles'] <= 200)
removed_distance = (~mask_distance).sum()
print(f"Removing {removed_distance:,} trips with invalid distances.")

# Filter Fare
mask_fare = (df['fare'] >= 0) & (df['fare'].notna())
removed_fare = (~mask_fare).sum()
print(f"Removing {removed_fare:,} trips with invalid fare amounts.")

# Pickup location bounds within chicago metro area
mask_lat = (df['pickup_centroid_latitude'] >= 41.6) & (df['pickup_centroid_latitude'] <= 42.1)
mask_lon = (df['pickup_centroid_longitude'] >= -88.0) & (df['pickup_centroid_longitude'] <= -87.4)
mask_location = mask_lat & mask_lon
removed_location = (~mask_location).sum()
print(f"Removing {removed_location:,} trips with pickup locations outside Chicago metro area.")

mask = mask_duration & mask_distance & mask_fare & mask_location
df = df[mask].reset_index(drop=True)

Removing 0 trips with invalid durations.
Removing 0 trips with invalid distances.
Removing 2,132 trips with invalid fare amounts.
Removing 0 trips with pickup locations outside Chicago metro area.

##### Drop Unnecessary Columns

In [31]:
cols_to_drop = ['trip_id', 'pickup_centroid_location', 'dropoff_centroid_location']

existing_drops = [col for col in cols_to_drop if col in df.columns]
missing_drops = [col for col in cols_to_drop if col not in df.columns]

df = df.drop(columns=existing_drops)

##### Final Validation and Memory Optimization