In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")

plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['figure.dpi'] = 100

In [3]:
df = pd.read_parquet('/Volumes/T7/DS Projects/Chicago Ride Demand Forecasting/data/processed/chirde.cleaned_data.parquet')
df.head()

,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,fare,tip,additional_charges,trip_total,shared_trip_authorized,shared_trip_match,trips_pooled,pickup_centroid_latitude,pickup_centroid_longitude
0,2024-12-31 23:45:00,2024-12-31 23:45:00,300.0,0.9,32,2.5,3.0,2.56,8.06,False,False,1,41.870605,-87.622169
1,2024-12-31 23:45:00,2025-01-01 00:00:00,860.0,4.6,6,15.0,0.0,4.50,19.50,False,False,1,41.949062,-87.661644
2,2024-12-31 23:45:00,2025-01-01 00:00:00,275.0,1.1,6,7.5,0.0,2.89,10.39,False,False,1,41.944225,-87.655998
3,2024-12-31 23:45:00,2024-12-31 23:45:00,588.0,0.6,8,5.0,0.0,2.63,7.63,False,False,1,41.890923,-87.618866
4,2024-12-31 23:45:00,2024-12-31 23:45:00,443.0,4.2,28,10.0,0.0,3.79,13.79,False,False,1,41.885281,-87.657234

In [4]:
df.shape

(4176957, 14)

In [5]:
df.describe()

,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,fare,tip,additional_charges,trip_total,trips_pooled,pickup_centroid_latitude,pickup_centroid_longitude
count,4176957,4176957,4.176957e+06,4.176957e+06,4.176957e+06,4.176957e+06,4.176957e+06,4.176957e+06,4.176957e+06,4.176957e+06,4.176957e+06,4.176957e+06
mean,2024-12-16 05:05:58.921625856,2024-12-16 05:15:39.595237888,5.798196e+02,2.564204e+00,2.505553e+01,1.015223e+01,7.641551e-01,3.279972e+00,1.419635e+01,1.057268e+00,4.188464e+01,-8.765841e+01
min,2024-12-01 00:00:00,2024-12-01 00:00:00,2.000000e+00,1.000000e-01,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,4.165022e+01,-8.791363e+01
25%,2024-12-08 01:00:00,2024-12-08 01:15:00,3.980000e+02,1.300000e+00,8.000000e+00,7.500000e+00,0.000000e+00,1.230000e+00,9.900000e+00,1.000000e+00,4.187061e+01,-8.767472e+01
50%,2024-12-15 12:15:00,2024-12-15 12:15:00,5.750000e+02,2.100000e+00,2.400000e+01,1.000000e+01,0.000000e+00,2.980000e+00,1.316000e+01,1.000000e+00,4.189207e+01,-8.764890e+01
75%,2024-12-23 00:15:00,2024-12-23 00:30:00,7.650000e+02,3.300000e+00,3.200000e+01,1.250000e+01,0.000000e+00,4.290000e+00,1.703000e+01,1.000000e+00,4.192276e+01,-8.762888e+01
max,2024-12-31 23:45:00,2025-01-01 00:15:00,9.990000e+02,2.000000e+01,7.700000e+01,2.000000e+02,8.300000e+01,3.037700e+02,3.262700e+02,3.900000e+01,4.202122e+01,-8.752995e+01
std,NaN,NaN,2.267370e+02,1.824993e+00,1.937711e+01,5.401021e+00,1.681140e+00,2.315335e+00,6.676846e+00,5.220341e-01,6.574957e-02,4.978310e-02

In [ ]:
df.isnull().sum()

trip_start_timestamp         0
trip_end_timestamp           0
trip_seconds                 0
trip_miles                   0
pickup_community_area        0
fare                         0
tip                          0
additional_charges           0
trip_total                   0
shared_trip_authorized       0
shared_trip_match            0
trips_pooled                 0
pickup_centroid_latitude     0
pickup_centroid_longitude    0
dtype: int64